apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    foo: bar
  name: prometheus-demo
  namespace: monitoring
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.default.svc:9115
  targets:
    staticConfig:
      labels:
        environment: prometheus.io
      static:
        - https://demo.do.prometheus.io/
        - https://prometheus.demo.do.prometheus.io/-/healthy
        - https://alertmanager.demo.do.prometheus.io/-/healthy
        - https://node.demo.do.prometheus.io/
        - https://grafana.demo.do.prometheus.io/api/health
